/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balancemaker.ui;

import javax.swing.JButton;
import javax.swing.border.TitledBorder;
import javax.swing.text.JTextComponent;
import org.jdesktop.swingx.JXButton;
import org.jdesktop.xswingx.BuddySupport;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author Red
 */
public class DebtPanel extends javax.swing.JPanel {
    private final int id;

    /**
     * Creates new form DebtPanel
     * @param id
     */
    public DebtPanel(int id) {
        initComponents();
        
        this.id = id;
        
        TitledBorder tb = (TitledBorder)getBorder();
        tb.setTitle(tb.getTitle() + id);
        
        setName(getName() + id);
        
        JTextComponent debtorEditor = ((JTextComponent)debtor.getEditor().getEditorComponent());
        PromptSupport.setPrompt("Debtor #" + id, debtorEditor);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, debtorEditor);
        
        amount.setPrompt("Amount owed");
        amount.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT);
        amount.addBuddy(close, BuddySupport.Position.RIGHT);
        // FIXME: Why doesn't the buddy button show? God..
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        debtor = new javax.swing.JComboBox<balancemaker.Buyer>();
        amount = new org.jdesktop.xswingx.JXTextField();
        jXSearchField1 = new org.jdesktop.xswingx.JXSearchField();

        close.setText("x");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Debt #"));
        setName("Name #"); // NOI18N

        debtor.setEditable(true);

        jXSearchField1.setText("jXSearchField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(debtor, 0, 248, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(debtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.xswingx.JXTextField amount;
    private javax.swing.JButton close;
    public javax.swing.JComboBox<balancemaker.Buyer> debtor;
    private org.jdesktop.xswingx.JXSearchField jXSearchField1;
    // End of variables declaration//GEN-END:variables
}
