/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balancemaker.ui;

import javax.swing.JButton;
import javax.swing.border.TitledBorder;
import javax.swing.text.JTextComponent;
import org.jdesktop.swingx.JXButton;
import org.jdesktop.xswingx.BuddySupport;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author Red
 */
public class DebtPanel extends javax.swing.JPanel {
    private final int id;

    /**
     * Creates new form DebtPanel
     * @param id
     */
    public DebtPanel(int id) {
        initComponents();
        
        this.id = id;
        
        TitledBorder tb = (TitledBorder)getBorder();
        tb.setTitle(tb.getTitle() + id);
        
        setName(getName() + id);
        
        JTextComponent debtorEditor = ((JTextComponent)debtor.getEditor().getEditorComponent());
        PromptSupport.setPrompt("Debtor #" + id, debtorEditor);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, debtorEditor);
        
        amount.setPrompt("Amount owed");
        amount.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT);
        amount.addBuddy(close, BuddySupport.Position.RIGHT);
        // FIXME: Why doesn't the buddy button show? God..
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        debtor = new javax.swing.JComboBox<balancemaker.Buyer>();
        amount = new org.jdesktop.xswingx.JXTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Debt #"));

        debtor.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(debtor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(debtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.xswingx.JXTextField amount;
    public javax.swing.JComboBox<balancemaker.Buyer> debtor;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JButton close = new JButton("x");
}
